### ISSUE TITLE
Consider an SDK suitable for use in containers (a runtime SDK)

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#101]
If you provision a cloud framework resource and then capture it in a lambda, you can easily invoke functions on it.  For example, tables

```typescript
let tab = new cloud.Table(..);
something.subscribe(() => {
    tab.insert({ id: x, ... }); // actually inserts into the table
});
```

This works great, but if you want to do similar things from within a container, you're out of luck.

In principle, I see no reason we couldn't version and ship an SDK that contains similar functionality but lets you connect up to the provisioned resources and use them directly.  There's probably a limit to how much we can abstract away the code in this case -- e.g., the implementation details leak through in that we need the DynamoDB table name -- but not having this seems like a big seam.

**Comment by lukehoban** [comment]
For AWS we have `aws.sdk`.  For `cloud` it's unlikely we'll do anything here in the near term - and will consider this as part of any broader re-design around this library.
