### ISSUE TITLE
Provide a local "emulator"?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#12]
We should consider whether to expose a local emulator for the Pulumi Platform which can be used to run programs on a development machine prior to pushing to the Pulumi Cloud.

Ideally, we would not need this, and could rely on dev/test being in the cloud.  That would allow us to focus on improving the inner loop experience with Pulumi Cloud.

However, we may find this is still too heavy-weight for rapid inner loop development.

In principle, we could provide a mock of the current Pulumi Platform surface area that runs locally.  But as we expand to SaaS and PaaS integrations, this may not be as easy.

**Comment by sohailalam2** [comment]
Hi @lukehoban @CyrusNajmabadi 
just wondering if you guys have given any further thought about local emulator which would simplify the dev cycle. 

I understand that test coverages does solve this to some extent however, it may not be applicable or useful for all situations. Having a local emulator would be of tremendous help. 

For example, the Serverless Framework provides excellent support for local development via plugins such as [serverless-offline](https://www.npmjs.com/package/serverless-offline), 
[serverless-dynamodb-local](https://www.npmjs.com/package/serverless-dynamodb-local), 
[serverless-s3-local](https://www.npmjs.com/package/serverless-s3-local) etc. 

Can we also get similar support in Pulumi where we can simply run the application locally without deploying it to the cloud?
