### ISSUE TITLE
Hangs when trying to use a feature in an unsupported region

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi-cloud#174]
Trying to deploy the exciting, new PPC bits to `us-west-1` just hangs on the step where it creates an EFS file system object.

Looking into the AWS console, you get a pretty clear message that "EFS is not available in US West (N. California). Please select another region."

Can we detect this situation and fail the update as necessary? Just hanging indefinitely probably isn't the ideal experience.

**Comment by lukehoban** [comment]
We won't try and tweak this ourselves.  Users can control this using the `aws: maxRetries` configuration parameter.
