### ISSUE TITLE
Avoid pushing Docker images when they haven't changed

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#183]
It would be nice if we could use the digest to avoid re-pushing Docker images that didn't actually change.  This gets cached by the server and we avoid pushing, but it takes many seconds of watching `Waiting` and `Layer already exists` messages printed to the console.

This is conceptually similar to what we do with assets, but I'm guessing we'll need to implement it all in the cloud framework JavaScript; for example, check to see if the image was built before building it, and if the digest doesn't change, we can skip the push (provided we know one succeeded before, which may require hitting the registry to ask, which may be more work than it's worth).

**Comment by lukehoban** [comment]
@pgavlin @mmdriley Have we addressed this as part of the recent `--cache-from` changes?  If not, what is the specific remaining work we are considering here?

**Comment by pgavlin** [comment]
I don't believe so, no. I think we're still pushing images even if they haven't changed.

**Comment by lukehoban** [comment]
This issue was moved to pulumi/pulumi-docker#32
