### ISSUE TITLE
Enable authentication on CloudEndpoint.static

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-cloud#188]
A common pattern is to serve static content that is protected by an OAuth token. Note that this is a feature supported by AWS API Gateway. Auth0 has a good tutorial on it: [Secure AWS API Gateway Endpoints Using Custom Authorizers](https://auth0.com/docs/integrations/aws-api-gateway/custom-authorizers)

**Comment by lukehoban** [comment]
We added support for this in `awsx` - but it's not clear there is going to be a multi-cloud way to do this - and we will likely revisit the mutli-cloud abstractions here more generally in the future.  Closing this out as an individual item.
