### ISSUE TITLE
Poor error experience from duplicate URN

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi-cloud#19]
The following code snippet:
```
api.routeStatic("GET", "/css/style.css", "css/style.css",              "text/css");
api.routeStatic("GET", "/css/style.css", "css/tachyons-4.3.7.min.css", "text/css");
```

yields the following error:
```
api.ts(271,20): error LUMI2010: Duplicate resource URN 'urn:lumi:homepage::stealthhp:index::aws:iam/role:Role::homepage48a37c4d5c40213c99d4dc5096cb5add870a1d6e'; try giving it a unique name
error: An error occurred while viewing the plan: One or more resource validation errors occurred; refusing to proceed
```

See what the problem is? The parameter "/css/style.css" is duplicated, and as a result Lumi will try to generate two objects with the same name. Which leads to a duplicate URN. Which is a problem.

The problem though is that the duplicate URN is listed, not anything related to the root cause ("/css/style.css"), although if you look closely you can see the name of the API object "homepage".

After a brief discussion with Luke, it sounds like this is a _really_ hard problem. So we might not be able to solve this generally or automatically. But in advance of shipping a new component, or finalizing our API design, we can probably take close attention to the error condition for when we encounter duplicate names for Pulumi resources.

**Comment by lukehoban** [comment]
This is effectively a part of https://github.com/pulumi/pulumi-cloud/issues/76.  Closing out and we can track general parameter validation there.
