### ISSUE TITLE
Create a more robust SSL story

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#192]
We hastily added some amount of HTTPS management in as our customers needed it (for instance, [this](https://github.com/pulumi/pulumi-cloud/pull/191)), but it leaves a fair bit to be desired around SSL and certificate management.  Further, we haven't been able to test it very thoroughly, since we don't have our own test certificates, etc.

We should revisit this after the dust has settled.

**Comment by lukehoban** [comment]
We have rich support for this in `awsx`, but will need to revisit the multi-cloud abstractions here more broadly before we can settle on clear path here.  Closing out this individual tracking issue for now.
