### ISSUE TITLE
Provide a way to used a fixed port with the mock provider

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-cloud#198]
I've been using the local mock implementation to get a tighter feedback loop in a small Pulumi program I'm developing, and it's actually a godsend since it makes it so much easier for someone like me who is not going to write JavaScript correctly the first time.

However. every-time I restart the web server (to pick up updates to my code), it picks a new port to serve on.  That means my pre-crafted curl command I run to post data (so I can test my code) has to be modified to use the correct port.

It would be great if I could specify someway (either in my program or in an environment variable like `PULUMI_MOCK_WEBSERVER_PORT`) a fixed port to listen on.

**Comment by lukehoban** [comment]
We now longer have a mock provider.
