### ISSUE TITLE
Failure to create a CloudFormation stack may leak the stack

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-cloud#203]
When CloudFormation stack creation fails, we roll back the stack. Though this generally completes successfully, it does not delete the stack itself: instead, the deleted stack sticks around in the `ROLLBACK_COMPLETE` state. See e.g. https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn:aws:cloudformation:us-west-2:153052954103:stack%2Fpulumi-ppc-pat-1-asg-stack-6e4b1ce825c5f559%2F1a389770-c588-11e7-9a8f-50a686fc379a

Successive updates will use new stack names, which leaks the original stack.

**Comment by MaxVynohradov** [comment]
@lukehoban faced with this issue
