### ISSUE TITLE
Implement a Kubernetes version of the cloud

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#227]
A Kubernetes version of our cloud will permit on-premises deployments, in addition to running in existing Kubernetes clusters.  This may also let us evolve our "mock" implementation to use minikube for more full-featured local development and testing that more closely mirrors a real production environment.

We should get a head start prototyping this, particularly as it will help teach us whether our current set of abstractions and shapes make sense.

This will, however, require https://github.com/pulumi/pulumi/issues/204.

**Comment by AaronFriel** [comment]
Hey @joeduffy, is this actively being worked on? I know OpenFaaS, Funktion, and KNative have made this a somewhat unstable area, what are your thoughts on what the underlying function orchestrator would be?

**Comment by joeduffy** [comment]
There unfortunately hasn't been much progress. @lukehoban can correct me, but I don't expect this to happen soon ish, primarily because we have been focused on hatching AWS, Kubernetes, etc specific packages to solve for many similar scenarios. Also, as you note, the current state of this area for Kubernetes is a bit all over the place.

**Comment by AaronFriel** [comment]
Understandable, thanks Joe. Always looking forward to your next blog post :)
