### ISSUE TITLE
Provision AWS volumes using EBS, not EFS

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#244]
We should consider provisioning volumes using EBS, and not EFS, for several reasons

* EFS is slow to provision
* EFS is slow at runtime
* EFS is limited in what regions it can run in
* EFS gives developers less granularity and control over IOPS, size, backup, restores, etc.
* It is my impression that EBS is the "gold standard" for what we're using EFS for

This is related, but orthogonal, to https://github.com/pulumi/pulumi-cloud/issues/175.  It is related because if we can get by using EBS, we may not need to provision an EFS filesystem at all.

**Comment by lukehoban** [comment]
We won't tackle this directly as-is.  We'll look at all-up re-review of surface area here - and storage technologies that can be supported cross-platform is a key part of that.
