### ISSUE TITLE
Support for different cloud.Function languages

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#266]
We had a customer request to run C# lambdas from within an otherwise JavaScript Pulumi program.  In principle, I see no reason this can't work.  In fact, if we do https://github.com/pulumi/pulumi-cloud/issues/168, it seems we would be very close to being able to do so.

The major challenge, I think, is going to be the "shimming" required to present a consistent function signature that is sufficiently insulated from the target cloud environment.  But given all the code rewriting we already do, I don't know that this is prohibitively complicated.

**Comment by lukehoban** [comment]
This issue was moved to pulumi/pulumi-aws-serverless#27
