### ISSUE TITLE
APIGateway logging and details metrics require account-wide configuration

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#319]
We want to enable logging and per-route metrics for API Gateway, to get insight into what is happening with the APIGateways backing our `HttpEndpoint`.

We can do that with the following:

```typescript
  const settings = new aws.apigateway.MethodSettings(name, {
            restApi: api,
            stageName: stageName,
            methodPath: "*/*",
            settings: [{
                metricsEnabled: true,
                loggingLevel: "INFO",
            }],
        });
```

However, the above will not work unless a CloudWatch logs ARN is provided for the account-wide (actually just region-wide within an account) `Account` - for example:

```typescript
 const apigatewayLogsRole = new aws.iam.Role(`${name}-api-logs`, {
            assumeRolePolicy: JSON.stringify({
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Sid": "",
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "apigateway.amazonaws.com",
                    },
                    "Action": "sts:AssumeRole",
                  },
                ],
            }),
        });
        const policy = new aws.iam.RolePolicyAttachment(`${name}-api-logs`, {
            role: apigatewayLogsRole,
            policyArn: aws.iam.AmazonAPIGatewayPushToCloudWatchLogs,
        });
        const accountSettings = new aws.apigateway.Account(name, {
            cloudwatchRoleArn: apigatewayLogsRole.arn,
        });
```

The problem is, each stack will overwrite the account-wide role that is used here.  

Technically, this might not be a problem, but it would be "strange" - for one, a given stack would think this was set to the value it set - but in reality it's likely the value drifted due to another stack.  But perhaps more concerning, this would overwrite anything the user had explicitly set themselves.

We have three options:
1. Don't try to get logs of detailed metrics from API Gateway
2. Require users to manually configure this in their account before being able to succesfully deploy `@pulumi/cloud` apps. 
3. Have every stack set this and overwrite each other per above.

**Comment by edgarrmondragon** [comment]
Hi @lukehoban, are there any updates or recommendations on this?
