### ISSUE TITLE
Do a first pass at Azure support

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#336]

**Comment by lukehoban** [comment]
@CyrusNajmabadi Worth updating this issue with the current plan of attack and roadmap?

**Comment by CyrusNajmabadi** [comment]
Will do.  https://github.com/pulumi/pulumi-cloud/pull/548 will add support for Task.  It also led to enough fixes across our stack for me to feel generally confident about our Azure story.

**Comment by CyrusNajmabadi** [comment]
cloud.Task is done.  working on cloud.Table.  Should be much easier :)

**Comment by CyrusNajmabadi** [comment]
I consider the first pass done at this point.  There is certainly lots of work to do here in the future, but we're at a healthy enough starting point to absorb that work in future milestones.
