### ISSUE TITLE
setComputeIAMRolePolicies needs to properly fit into the new dependency system.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-cloud#386]
Found during: https://github.com/pulumi/pulumi-ppc/pull/245

Right now we have an API set for callers to set the role policies to be used by different pulumi cloud component (like Functions and Services).  However, currently, this doesn't play well with the Output<T> system.  That's because people like the ppc need to set these (using output values), but you can only set this using output values if you call it asynchronously.  However, if you call it asynchronously then you can't guarantee that hte values will be set by the time the next Function/Service needs it.

This API should really accept pulumi.Inputs.

However, a brief investigation into making that change ended up causing problems later on when producing RolePolicyAttachments due to https://github.com/pulumi/pulumi-cloud/issues/278

We need a solution that works properly here and doesn't cause any additional problems.

**Comment by lukehoban** [comment]
We have an answer here currently, and no clear plans to do anything in the near term.  We'll likely broadly revisit the config story as part of https://github.com/pulumi/pulumi-cloud/issues/134.  Closing this out.
