### ISSUE TITLE
Make log retention configurable

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#398]
Today we hardcode log retention for functions and services at 1 day, and rely on the log aggregator as the only long term storage of logs.  

We should at least make this configurable, and should possibly default to retaining all logs, with the option to opt-in to expiring logs for cost savings if users want to opt-in to it.

**Comment by CyrusNajmabadi** [comment]
Note: in teh awsinfra work i'm doing, a TaskDefinition's logGroup can be provided by teh user, giving them full control over this.  So the potential work items here are:

1. Do we provide a way when creating an aws.CallbackFunction to configure logging?  Right now, we do not seem to do anything special with setting up logging there, and we might want to consider it.
2. Do we provide some mechanism at the Cloud layer to control this?  
3. if we do provide a mechanism for this at the Cloud layer, is it some sort of global mechanism, or is it something you can somehoe configure on a per lambda basis?

**Comment by albertocorrales** [comment]
We also hit this issue, and we had to create the log Groups before creating the lambda has it is described here: https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#cloudwatch-logging-and-permissions.

However, it would be great if the object aws.lambda.Function had a parameter to define the retention days for logs.

**Comment by pavelescurazvan** [comment]
This issue is still present - there is no way to configure the retention period for Lambdas created with Pulumi
