### ISSUE TITLE
Align HttpAPI more closely with Express

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#4]
We should try to align HttpAPI more closely with Express/Connect - in particular:
* [x] `req`/`res` signatures (done in 7427628)
* [x] Per-route middleware (done in #26)
* [ ] Shared middleware
* [ ] View rendering
* [ ] Routers

There may be some challenges adopting this model to Lumi's environment where there is a distinction between deployment-time and run-time.  We will need to explore where and how we need to intentionally diverge given these constraints.

**Comment by CyrusNajmabadi** [comment]
We have an approach that was introduced last milestone that works well.  Namely, the introduction of the HttpServer API.   This gives a high fidelity bridge to the node http world, and takes us out of the unpalatable space of trying to invent an alternative that has to be as capable as that entire ecosystem. However, i'd like to keep this issue around to use for tracking deprecating API and having a fully fleshed out alternative for it.
