### ISSUE TITLE
Make it easy to add a custom domain to HttpEndpoint and cloud.Service

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-cloud#462]
Per @chrsmith's feedback [here](https://github.com/pulumi/pulumi-service/issues/220#issuecomment-382105940):

> - In the `pulumi-cloud` suite of packages, can we make it easy to create `cloud.Service` and `cloud.HttpEndpoint` that is served from a user-controlled domain. This means providing ways to configure the load balancer, DNS, and maybe certificates in a "as much as possible" cloud provider agnostic manner.

This isn't a critical improvement, so I'm just assigning to M16. But, it may be useful to consider the scenario as part of the current design work.

**Comment by c0bra** [comment]
After having just gone through creating a service at AWS, this would be very handy.  Especially being able to stand up an ALB automatically with routing so you don't have to be running a separate balancer per service at $16/mo.

**Comment by lukehoban** [comment]
We are adding AWS-specific libraries for working with ECS Services and APIGateways as part of pulumi/pulumi-aws-infra#53. In the near term, those will offer greater flexibility to control details like this for users who are working with AWS. We'l continue to think about how to add cross-cloud support for this as part of the cloud package.
