### ISSUE TITLE
Make service health checks configurable

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi-cloud#498]
When a service specifies `protocol: "http"` for one of its ports, we should allow customization of at least:
- the health check URL
- the set of healthy responses

Full set of ELB health check options: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html

**Comment by lukehoban** [comment]
Related to this - we also had a request to expose configuration of `healthCheckGracePeriodSeconds` as part of overall health check configuration on `cloud.Service` (or possibly initially just even `cloudaws.Service`.

**Comment by lukehoban** [comment]
We are adding AWS-specific libraries for working with ECS Services as part of pulumi/pulumi-aws-infra#53. In the near term, those will offer greater flexibility to control details like this for users who are working with AWS. We'll continue to think about how to add cross-cloud support for this as part of the cloud package.
