### ISSUE TITLE
GCP Support

### ISSUE THREAD

**Issue by sohailalam2** [pulumi/pulumi-cloud#518]
Great work guys!! I just came to know about Pulumi a few days ago... so far everything looks nice and very useful. 

I was wondering what are supports for GCP like? Is there a roadmap when *cloud-gcp* will be out?

Thanks for the great work!

**Comment by lukehoban** [comment]
We're eager to bring up GCP support for `@pulumi/cloud`.  We don't have a fixed roadmap yet, and will be happy to collaborate with anyone interested in helping out here.

We have support for raw GCP resources as part of https://github.com/pulumi/pulumi-gcp.  On top of this, it's possible to create higher-level support for functions along the lines of https://github.com/pulumi/pulumi-gcp/pull/12.  Opened https://github.com/pulumi/pulumi-gcp/issues/24 to explicitly track this.  Much of the API in `cloud-gcp` can build on top of this.

There will be a couple big open questions:
1. Which GCP resources will be used as the implementation for each high-level concept - for example - `Table`, `Topic`, `timer`, `API`, etc.
2. How will functions and event sources be wired together?
3. How will `cloud.Service` and `cloud.Task` be supported on GCP?  Will these run on GKE?  

If folks are interested in contributing in any of these areas, thoughts and PRs are welcome.  Implementations of any parts of the API as independent examples can be a great starting point in several of these areas.
