### ISSUE TITLE
Weird docker cache behavior with Cache From builds

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-cloud#523]
In one of our customer stacks, we observed some super bizarre behavior with `cacheFrom` on a service build.  In this case we have a multistage build, where the first stage has an explicit name and the second stage just copies some artifacts from the first build.  The behavior we observed:

- During the initial deploy, there was no caching.  Both stages were built.  This is expected.
- During the second deploy (with no changes) there were cache hits for the first build stage, but not for the second.  This caused the ECS services to be updated because a "new" image was built and tagged.
- During the third deploy (again with no changes) both builds got cache hits and the service ECS services were not updated (as expected).

We saw this behavior across three stacks.  It's unclear why the docker builds behave in this error.

If necessary, I can provide links to deployment logs.

**Comment by joeduffy** [comment]
@CyrusNajmabadi I wonder if this is related to what you were observing last evening?

**Comment by CyrusNajmabadi** [comment]
This should be fixed now with https://github.com/pulumi/pulumi-docker/pull/34. I now repro the behavior where on the second deploy all my builds get cache hits.  

If you see differently, let me know.  There may be something particular about this setup that is different to how i tried to repro things.
