### ISSUE TITLE
cloud.timer.interval won't work for Azure

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-cloud#605]
The following code, configured for Azure:

```
import * as cloud from "@pulumi/cloud";

let interval = cloud.timer.interval('testinterval', { minutes: 30 }, () => {
    console.log('Running...');
    return Promise.resolve();
});
```
deploys successfully but the Function App throws
`Function (testinterval) Error: '00:30:00' is not a valid CRON expression.`

Because `function.json` contains `"schedule":"00:30:00"`  which is not CRON expression.

I'm not sure you can actually do proper intervals with CRON expressions?

Version of `pulumi-cloud`: `0.15.1`

**Comment by CyrusNajmabadi** [comment]
That's odd.  The documentation says it should work:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#timespan

We also have tests for this here: https://github.com/pulumi/pulumi-cloud/blob/master/examples/timers/index.ts

The only thing i notice from the docs is this: A TimeSpan can be used only for a function app that runs on an App Service Plan.

Is it possible you're not on such a plan?

**Comment by mikhailshilkov** [comment]
Hm, ok, I don't run on App Service Plan, I run on Consumption Plan.
But nobody does: `timer.interval` is using `Subscription` which is using `FunctionApp` which is Consumption Plan.
Are those tests actually running in Azure?

**Comment by CyrusNajmabadi** [comment]
Yup.  They do run in azure.  For example: https://travis-ci.com/pulumi/pulumi-cloud/jobs/147715132

```
[ i/pulumi-cloud/examples/timers ] Wrote output to /tmp/p-it-travis-job-timers-a4e23b0c-022613273/command-output/yarn-link.20180925-083424.daea8.log
[ i/pulumi-cloud/examples/timers ] projdir: /tmp/p-it-travis-job-timers-a4e23b0c-022613273
[ i/pulumi-cloud/examples/timers ] Initializing project (dir /tmp/p-it-travis-job-timers-a4e23b0c-022613273; stack p-it-travis-job-timers-a4e23b0c)
[ i/pulumi-cloud/examples/timers ] **** Invoke '/home/travis/.pulumi/bin/pulumi login --cloud-url https://api.pulumi.com --tracing [secure]' in '/tmp/p-it-travis-job-timers-a4e23b0c-022613273'
```

**Comment by mikhailshilkov** [comment]
I'm not exactly sure how to read those logs. Just in case - my app deploys just fine, but timer won't fire complaining about the schedule format.

**Comment by CyrusNajmabadi** [comment]
Interesting, can you point me at any logs?  I can try to take a look!

**Comment by CyrusNajmabadi** [comment]
Actually, i can repro this, and i know what happened.  And clearly test coverage is not sufficient here.  I'll take care of this.  thanks for bringing it to our attention!
