### ISSUE TITLE
Add a SQL database abstraction

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#63]
We currently support NoSQL database tables by way of the `cloud.Table` resource.  We've already gotten customer requests for SQL tables, however, which is entirely reasonable, and I predict will be a common request, especially for Enterprise developers.  It seems we could pick a specific database like MySQL that we know can be run in all clouds and on-premises, and then just bless that.

Let's call this `cloud.Database`:

    let db = new cloud.Database({
        customers: { ... },
        orders: { ... },
    });
    something.subscribe(() => {
        for (let row of await db.query("SELECT * FROM customers WHERE p")) {
            process(row);
        }
    });

Clearly there are many hard problems locked away behind the notion of `customers...orders...`.

Perhaps the biggest challenge is what to do with schema and schema updates.  We already have this challenge, tracked by https://github.com/pulumi/pulumi-cloud/issues/43, although arguably with SQL it gets much more complex.  The NoSQL tables we offer do have some "schema" in the form of indices, but it's far less rigorous a notion, and developers tend to write code to be resilient in the face of schema deltas with NoSQL, whereas with SQL stuff just starts to break.

We have discussed the idea of ["sequenced deployment actions"](https://github.com/pulumi/pulumi/issues/127) in the past, which is similar to how Google manages such problems during deployments internally.  In conjunction with a first class way of managing schema in a way that Pulumi can "see" -- so it can do diffs and apply deltas -- this could be reasonable.  But there definitely be dragons there and this deserves much more think-time.

**Comment by bionicles** [comment]
I would love to use Pulumi to manage Schema diffing / migrations 

If the Pulumi user could define SQL schema in nodejs in a declarative way it would be hugely valuable
