### ISSUE TITLE
Auto-GC unused Docker images

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#638]
_From @joeduffy on October 16, 2017 15:33_

At some future date, developers will be deploying containers to Pulumi, and they are going to love it.  At some slightly-later date, they will then realize that their private registries -- many of which we create on their behalf -- are full of junk: unused, old, and unneeded images and layers.

We will need a solution to auto-garbage collecting these.  Particularly if the registry is a mere implementation detail and developers don't think in terms of custom registries whose contents they carefully manage and version and so on, we can be fairly aggressive here.

Perhaps we can leverage something like this: https://aws.amazon.com/about-aws/whats-new/2017/10/introducing-lifecycle-policies-for-amazon-ec2-container-registry/

_Copied from original issue: pulumi/pulumi-service#215_

**Comment by joeduffy** [comment]
_From @lukehoban on October 16, 2017 15:37_

Should this be in the pulumi-cloud repo?  I had imagined we would solve for this there in a platform-specific way related to the inplementation technique we use for our container support on a given target platform.

I suppose if/when we build our own multitenant Pulumi cloud as a backend used by the Pulumi service, that might also independently want to solve this - but I’ve imagined that to be further down the road.

**Comment by joeduffy** [comment]
I added it here intentionally to track the broader issue, as I wasn't sure what side of the open source line it falls on.  (pulumi-cloud is open source, pulumi-service is not.)  This is the kind of value add policy I can easily imagine will be a combination of the two.  If there are specific mechanisms we need to add to pulumi-cloud, however, I would definitely add them there.

**Comment by joeduffy** [comment]
_From @lukehoban on October 16, 2017 23:23_

We haven't implemented anything that creates ECR registries yet - but we will as part of https://github.com/pulumi/pulumi-cloud/issues/87.  

As part of that, I was planning on just have the default policy be to only maintain the latest image, since we won't have any useful way for users to revert back via the registry itself anyway, so there's no value in maintaining them.  Assuming we do that, I don't think there will be anything else we need to do in the service.

**Comment by joeduffy** [comment]
_From @chrsmith on February 9, 2018 21:36_

@lukehoban is this still needed? We do GC of docker containers that are built on the PPC, but only based on available disk space, not due to usage, etc.

**Comment by joeduffy** [comment]
_From @lukehoban on February 9, 2018 21:46_

I think we may still need to do this. We should move this to the pulumi-cloud repo to do what I outlined above (which I don’t believe we have implemented yet).

**Comment by lukehoban** [comment]
This was fixed with 
https://github.com/pulumi/pulumi-cloud/pull/556
