### ISSUE TITLE
Creating vpclinks (from apigateway 'proxy' routes) failing in us-east-2 during tests.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-cloud#666]
Cloud tests have been failing consistently because AWS tells us we've maxed out vpc links in us-east-2.  For example: https://travis-ci.com/pulumi/pulumi-cloud/builds/91798123

```
[ lumi-cloud/examples/containers ]  +  aws:apigateway:VpcLink examples-containers7d5cd3e1 creating error: Plan apply failed: BadRequestException: There are too many Vpc Links defined for this account. Limit is 5
[ lumi-cloud/examples/containers ]  +  aws:apigateway:VpcLink examples-containers7d5cd3e1 **creating failed** error: Plan apply failed: BadRequestException: There are too many Vpc Links defined for this account. Limit is 5
```

This test only creates a single vpclink, and as far as @lukehoban  and I can tell, there are no vpclinks in that account/region.  So something is seriously strange.  We've opened a ticket with AWS.  But, in the meantime, i'm disabling vpclink testing for us-east-2 here: https://github.com/pulumi/pulumi-cloud/pull/665

We still get testing of this with fargate (which runs in us-east-1).  Over there things still pass: https://travis-ci.com/pulumi/pulumi-cloud/builds/91800123

**Comment by lukehoban** [comment]
We got the limit increase.  We can try to reenable this test now to see if that addressed the issue.

**Comment by lukehoban** [comment]
This is no longer failing.
