### ISSUE TITLE
Mapping between creating of Cluster with aws-infra

### ISSUE THREAD

**Issue by graforlock** [pulumi/pulumi-cloud#676]
I have the need to initialise ECS Cluster with a custom VPC ID. I am trying to fork tutorial example, it is:

```javascript
const cloud = require('@pulumi/cloud-aws');
const aws = require('@pulumi/aws');
const infra = require('@pulumi/aws-infra');

let vpc = new aws.ec2.Vpc('vpc', {
  name: 'nginx-cluster-vpc',
  cidrBlock: '10.0.0.0/16'
});

let cluster = new infra.Cluster('cluster' , {
  name: 'nginx-cluster',
  network: {
    vpcId: vpc.id,
    subnetIds: [ '10.0.0.0/24' ]
  }
});

let nginx = new cloud.Service('nginx', {
  name: 'nginx-task',
  containers: {
      nginx: {
          build: './app',
          memory: 128,
          ports: [{ port: 80 }],
      },
  },
  replicas: 2,
});

exports.url = nginx.defaultEndpoint.apply(e => `http://${e.hostname}`);
```
At the moment the code creates two separate ECS clusters without any glue.

But, is is possible to reference this cluster created with `aws-infra` with the container tasks that would be used from the cloud package?

If not, is there a way to configure custom cluster VPC ID in the cloud package upon creating Services cluster? I need the custom VPC for including a RDS PostgreSQL cluster.

It is, nonetheless, completely achievable in Fargate via GUI wizard: https://docs.subzero.cloud/images/fargate/cluster-config.png

**Comment by lukehoban** [comment]
You should be able to use `cloud.config.setEcsCluster(...)` to set up the ECS cluster to use for all `cloud.Service` instances.  You have to make sure to call that before creating the Services.

We're at work on a library that is more AWS ECS/Fargate specific but still generally as simple to use as `cloud.Service` that will more flexibly address this kind of scenario in https://github.com/pulumi/pulumi-aws-infra/issues/53.  Initial versions of that will be published very soon, and it may be worth taking a look at that when it comes out.

**Comment by lukehoban** [comment]
Closing this out - as I believe the reply above should address the question here - but please reopen if there are further questions/issues here.
