### ISSUE TITLE
AWS Binary media types toggles on every deploy

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-cloud#725]
**Affected component**: `cloud.API` deployments on AWS
**Impact**: makes API responses unusable 50% of the time
**Pulumi CLI version**: 0.17.8

## Summary
When making any change on a cloud api (adding or changing a route) which causes:
- update of `aws:apigateway:RestApi`
- replacement of `aws:apigateway:Deployment`
- update of `aws:apigateway:Stage`

The setting for the API gateway Binary Media Types toggles between `*/*` or none.

## Steps to reproduce

1. Create a basic api with a single route.
2. Run `pulumi up`
3. Observe "Binary Media Types" will be set to `*/*` - API responses will work correctly
4. Change or add a route to cause an update of the RestApi
5. Re-run `pulumi up`
6. Observe "Binary Media Types" will be removed causing API responses to appear as base64 strings

Each subsequent update of the RestApi will alternate the "Binary Media Types" being set correctly or being removed.

## Expected behaviour
"Binary Media Types" should always be set to `*/*`

**Comment by ellismg** [comment]
Thanks for the detailed report, @danielrbradley, @CyrusNajmabadi can you take a look?  I wonder if we have a similar problem in awsx as well?

**Comment by CyrusNajmabadi** [comment]
Very crazy.  Thanks for letting us know!  I'll try to repro this.  If i can't, i'll reach out for further information in case there's something specific about your config here.

**Comment by danielrbradley** [comment]
@CyrusNajmabadi here's the code I used to test: https://github.com/danielrbradley/pulumi-repro-1

**Comment by leezen** [comment]
I used your repro and wasn't able to reproduce the issue. Looking at the diff details, the RestApi body still contained the */* binary media types set. Closing, but please feel free to re-open if you are still seeing this.
