### ISSUE TITLE
API route with trailing / causes permission issues on AWS

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-cloud#726]
Writing a route as:
```ts
api.get('/foo/', (req, res) => {...
             ^
```
instead of
```ts
api.get('/foo', (req, res) => {...
             ^
```
causes the permissions to break on AWS - meaning that API Gateway cannot invoke the Lambda function, and the following error is displayed when viewing the API Gateway trigger on the lambda: `The API with ID xxxxxxxx does not include a resource with path /foo/ having an integration arn:aws:lambda:[REGION]:[ACCOUNT]:function:[FUNCTION] on the GET method.`

## Possible Solution
Ignore any trailing slash from routes before creating the resources.

**Comment by CyrusNajmabadi** [comment]
If we do something here, it will probably be to validate and throw if hte path isn't something acceptable.  :)
