### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#738]
Three tests are currently failing with:

```
 pulumi:pulumi:Stack table-p-it-travis-job-table-b0c07e08 creating Error: Secret outputs cannot be captured by a closure.
```

This was caused by https://github.com/pulumi/pulumi-terraform/pull/427 (and exacerbated by https://github.com/pulumi/pulumi/issues/2718).

**Comment by stack72** [comment]
@lukehoban this is now passing because we reverted the secrets feature in the main providers https://travis-ci.com/pulumi/pulumi-cloud/builds/121342567
