### ISSUE TITLE
Get rid of @pulumi/azure-serverless dependency

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-cloud#747]
The Azure implementation depends on [the deprecated package `@pulumi/azure-serverless`](https://github.com/pulumi/pulumi-azure-serverless). That deprecated package seems incompatible to `pulumi-azure 1.0.0` too.

We should refactor to rely on serverless helpers in `pulumi-azure` itself.

**Comment by leezen** [comment]
With the Azure 2.0 stuff, this seems more pressing since the examples no longer work and there are breaking changes in `@pulumi/azure` that are incompatible with `@pulumi/azure-serverless`
