### ISSUE TITLE
No logs on AWS

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#791]
This program creates a lambda that cannot write logs to CloudWatch.

```ts
import * as cloud from "@pulumi/cloud-aws";
let endpoint = new cloud.API("hello-world");
endpoint.get("/", async (req, res) => {
    console.log("hello world")
    res.status(200).json({hello: "world"});
});
exports.endpoint = endpoint.publish().url;
```

`pulumi logs` returns no results, and the Lambda console includes:

<img width="486" alt="Screen Shot 2021-05-24 at 10 54 51 AM" src="https://user-images.githubusercontent.com/223467/119282861-82207b00-bc7e-11eb-91c8-9a3273bf9f1b.png">

**Comment by leezen** [comment]
This was broken in https://github.com/pulumi/pulumi-cloud/pull/783 -- a workaround will be to explicitly set `cloud-aws:computeIAMRolePolicyARNs` in config with the appropriate policy ARNs. I'll submit a PR to have this match the set of policies we default to in `@pulumi/aws` plus the existing ECS policy.
