### ISSUE TITLE
Better support for inline programs

### ISSUE THREAD

**Issue by hbj** [pulumi/pulumi-cloud#794]
Currently the cloud config (more specifically `cloud:provider`) is being loaded when the `@pulumi/cloud` package is imported. This is fine for local programs, but for inline programs this is too early as the configuration will be set programmatically after creating the stack. In this case the import instruction will throw an error saying that the `cloud:provider` config option is missing.

One way to work around this is to require the `@pulumi/cloud` package inside the inline program to make sure it only gets loaded when the program is executed and the stack is configured correctly. But it would be nice the have the package load the configuration as late as possible, when it becomes really needed during the program execution, so we don't have to use the described workaround.

**Comment by lukehoban** [comment]
This is most likely due to https://github.com/pulumi/pulumi/issues/5582.  I expect we will likely fix via addressing that, instead of changing anything in `@pulumi/cloud`.  If we do decide we cannot fix Automation API here - we may need to revisit the pattern used here and elsewhere.
