### ISSUE TITLE
Missing Github release vs NPM registry

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-cloud#838]
### What happened?

It appears the latest release on this repository is `0.40.1`, but looking at NPMjs, the latest version is `0.40.2`.
There's a `0.40.2` tag dating back to July 2023, but NPMjs indicates that same version was published in late November 2023, which matches with the latest commit in this repo.

### Example

n/a	

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Added the GitHub release as well.  The tag was already there though - the release shouldn't strictly be necessary for anything.

https://github.com/pulumi/pulumi-cloud/releases/tag/v0.40.2
