### ISSUE TITLE
Migrate from aws.s3.Bucket to aws.s3.BucketV2

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-cloud#845]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider migrating from aws.s3.Bucket to aws.s3.BucketV2.

See also: https://github.com/pulumi/home/issues/3583

**Comment by t0yv0** [comment]
Discovered this project through pulumi/examples scan for the use of aws.s3.Bucket.

**Comment by mjeffryes** [comment]
You can skip this one (see https://github.com/pulumi/pulumi-cloud/issues/844)
