### ISSUE TITLE
Create public `pulumi` Dockerhub account and images

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#85]
For our container support in `@pulumi/cloud` we will have a few base images that we'll need to make available in the public Docker hub.

None of the currently planned images have anything especially interesting in them - so we probably can/should publish from their "official" names sooner rather than later.

**Comment by lukehoban** [comment]
We have a shared `pulumi` DockerHub account now - but we do not currently expect to invest in the `nodejsrunner` image.  If we do, we'll definitely move it - but we do not need to track this on it's own.

**Comment by Lepozepo** [comment]
@lukehoban is the source for your `nodejsrunner` image available publicly anywhere? Thanks in advance!
