### ISSUE TITLE
Expose streaming capability from Table

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#97]
I was tinkering with some cloud collections libraries, with streaming helpers and whatnot, and it would be really nice to be able to `subscribe` to a `Table`'s updates.  This would enable some fairly powerful patterns of infrastructure, like streams processing pipelines.

At the moment, we don't expose a hook for the underlying AWS DynamoDB Tables event hooks.

Of course, in the meantime, we can just do everything on `Topic`s which already implement `cloud.Stream<T>`.  But we may want to enable this on persistent stores too, for Spark-like scenarios.

**Comment by lukehoban** [comment]
We will likely reconsider several things in this library in the future - but this is a fairly specific ask that hasn't been a major point of feedback over the last 2 years, so will close this one out.
